name: Build Test

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: 'stable'
          check-latest: true
      - run: go mod download
      - run: pwd
      - run: env
      - run: go build -o tamo ./cmd/tamo
