name: Release Binaries

on:
  release:
    types: [created]

jobs:
  build:
    name: Build and Upload Release Assets
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 'stable'
          check-latest: true
          
      - name: Get release info
        id: get_release
        uses: actions/github-script@v6
        with:
          script: |
            const release = await github.rest.repos.getRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: context.payload.release.id
            });
            core.setOutput('upload_url', release.data.upload_url);
            
      - name: Build Linux AMD64 binary
        run: |
          GOOS=linux GOARCH=amd64 go build -o tamo-linux-amd64 ./cmd/tamo
          
      - name: Build Linux ARM64 binary
        run: |
          GOOS=linux GOARCH=arm64 go build -o tamo-linux-arm64 ./cmd/tamo
          
      - name: Build Darwin ARM64 binary
        run: |
          GOOS=darwin GOARCH=arm64 go build -o tamo-darwin-arm64 ./cmd/tamo
          
      - name: Upload binaries to release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            tamo-linux-amd64
            tamo-linux-arm64
            tamo-darwin-arm64
          tag_name: ${{ github.event.release.tag_name }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
