name: Release Binaries

on:
  release:
    types: [created]

jobs:
  build:
    name: Build and Upload Release Assets
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 'stable'
          check-latest: true
          
      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.3.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
          
      - name: Build Linux AMD64 binary
        run: |
          GOOS=linux GOARCH=amd64 go build -o tamo-linux-amd64 ./cmd/tamo
          
      - name: Build Linux ARM64 binary
        run: |
          GOOS=linux GOARCH=arm64 go build -o tamo-linux-arm64 ./cmd/tamo
          
      - name: Build Darwin ARM64 binary
        run: |
          GOOS=darwin GOARCH=arm64 go build -o tamo-darwin-arm64 ./cmd/tamo
          
      - name: Upload Linux AMD64 binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./tamo-linux-amd64
          asset_name: tamo-linux-amd64
          asset_content_type: application/octet-stream
          
      - name: Upload Linux ARM64 binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./tamo-linux-arm64
          asset_name: tamo-linux-arm64
          asset_content_type: application/octet-stream
          
      - name: Upload Darwin ARM64 binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./tamo-darwin-arm64
          asset_name: tamo-darwin-arm64
          asset_content_type: application/octet-stream
